project_id = "bhjkkyxyfqrtcnbkyilr"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.hook.send_email]
enabled = true
uri = "functions/v1/send-auth-email"

[functions.mistral-ai]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.medicine-info]
verify_jwt = false

[functions.scan-medicine-image]
verify_jwt = false

[functions.diet-recommendation]
verify_jwt = false

[functions.diet-chat]
verify_jwt = false

[functions.check-medicine-reminders]
verify_jwt = false

[functions.drug-interactions]
verify_jwt = false

[functions.prescription-ocr]
verify_jwt = false
